# Generated by Django 4.2.17 on 2024-12-30 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user_email',
        ),
    ]
