# Generated by Django 4.2.17 on 2024-12-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_reservation_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
