# Generated by Django 4.2.17 on 2024-12-30 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=123456789, max_length=12, validators=[django.core.validators.RegexValidator(message="Numer telefonu musi być w formacie: '+48123456789' lub '123456789' (bez spacji i znaków specjalnych).", regex='^(\\+48)?\\d{9}$')]),
            preserve_default=False,
        ),
    ]
